trakt/calendar.py
trakt/sync.py
trakt/tv.py
trakt/users.py

follow dece4d0a1b453412f9e7f92a938232487977bffd
Actually, to get the show of a **TVEpisode** we only have show name (`self.show`) which is not reliable because some shows have the same name.
The show trakt id is more reliable than show name because it is unique. This PR adds `show_id` attribute to **TVEpisode**.
__Example :__  [Top Boy](https://trakt.tv/shows/top-boy) and [Top Boy 2019](https://trakt.tv/shows/top-boy-2019)
A TVEpisode from [Top Boy 2019](https://trakt.tv/shows/top-boy-2019) uses slug `top-boy` (made from `slugify(self.show)` ) instead of `top-boy-2019` to fetch data from trakt api. Therefore data received is wrong.

add show_id to TVEpisode

---

trakt/sync.py

Improve https://github.com/moogar0880/PyTrakt/pull/196.
This allows the caller to pass progress value in the same go.
I would not want to call `update(progress)` before calling `stop()` just to get accurate progress, because that would make two API calls to trakt.tv.
Required by:
- https://github.com/Taxel/PlexTraktSync/pull/1131

Feature: Add progress parameter to Scrobbler methods

---

trakt/movies.py

Various calls to `extract_ids` create the `trakt` property. Add the initializing to IDE typing would not consider property unknown.
For example:
- https://github.com/Taxel/PlexTraktSync/blob/88dc3fd97e603f73316d5bd393bce9f7447aeb94/plextraktsync/sync.py#L119
Relates to some older bug report:
- https://github.com/moogar0880/PyTrakt/issues/158

Initialize Movie.trakt property with None

---

tests/test_shows.py
trakt/mixins.py

Fix https://github.com/glensc/python-pytrakt/pull/14
`Person` and `TVSeason` `_build` methods are different, they call `ids` first before `_ids`, so therefore we need setter for `ids`. Unfortunately, that data is not even tested, so this did not come out in any way.
Typically it's like this:
- https://github.com/glensc/python-pytrakt/blob/b5dfbeb86b9cad87dd8b9781a3ab9873cf503a6d/trakt/movies.py#L125-L131
but `Person` and `TVSeason` have:
- https://github.com/glensc/python-pytrakt/blob/b5dfbeb86b9cad87dd8b9781a3ab9873cf503a6d/trakt/people.py#L64-L70
- https://github.com/glensc/python-pytrakt/blob/b5dfbeb86b9cad87dd8b9781a3ab9873cf503a6d/trakt/people.py#L64-L70

Fix ids setter for Person and TVEpisode

---

trakt/errors.py

This gives 500 error right now:
- https://api-v2launch.trakt.tv/shows/game-of-thrones?extended=full
```
HTTP/2 500
date: Mon, 12 Dec 2022 05:38:15 GMT
content-type: text/html
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-download-options: noopen
x-permitted-cross-domain-policies: none
referrer-policy: strict-origin-when-cross-origin
cache-control: no-cache, no-store
x-error-message: Internal server error. Please open a support issue and include your full API request and response, including all headers.
vary: Accept-Encoding
x-request-id: cbb03120-fdbe-46ba-b7e9-1311c7359474
x-runtime: 0.004596
cf-cache-status: BYPASS
server: cloudflare
cf-ray: 77841cdccebac7f7-TLL
```
expose the `x-error-message` header value via `e.error_message`.

Expose x-error-message header via error_message property

---

trakt/errors.py

Similarly to https://github.com/glensc/python-pytrakt/pull/18 extend error class.

Add retry_after property to RateLimitException

---

trakt/tv.py
trakt/users.py

Let `TVShow` handle creating `TVSeason`, which will create `TVSeason` which will create ` TVEpisode` objects themselves rather than building them "outside".
This fixes issue that `show_collection[].seasons[].episode` is raw json rather `TVEpisode` object.
Required for https://github.com/Taxel/PlexTraktSync/pull/1377

Refactor: show_collection: Pass all data to TVShow()

---

tests/mock_data/users.json
trakt/users.py

There's been an update of Trakt API adding a `share_link` value to lists :
```json
"list": {
"name": "IMDB: Top Rated Movies",
"description": "The IMDB top 250 movies, based on popularity. List updated daily.",
"privacy": "public",
"share_link": "https://trakt.tv/lists/2142753",
"type": "personal",
"display_numbers": true,
"allow_comments": true,
"sort_by": "rank",
...
```
This PR adds this keywork to Userlist class to comply with trakt API update.
fixes https://github.com/Taxel/PlexTraktSync/issues/1456

Add share_link to UserList tuple

---

trakt/core.py
trakt/mixins.py
trakt/movies.py
trakt/tv.py
trakt/users.py

_Replaces https://github.com/moogar0880/PyTrakt/pull/190_
- https://docs.python.org/3/library/typing.html#typing.NamedTuple
NOTE: there appears `Translation` being present in `movie.py` and `tv.py`. and they are not even identical.
NOTE: Can't have `NamedTuple` and `__init__`, so `UserList` stays as `namedtuple()`
UPDATE: Copied `DataClassMixin` trick from:
- https://github.com/glensc/python-pytrakt/pull/29#issuecomment-1513737815

Refactor: Use NamedTuple typing

---

requirements.txt
trakt/mixins.py
trakt/users.py

Improves https://github.com/glensc/python-pytrakt/pull/29
Uses [`@dataclass`](https://docs.python.org/3/library/dataclasses.html) and its valid properties to create `UserList` class.
The other classes should be updated too. Leaving that for the future.

Refactor: Update DataClassMixinClass to pass only defined properties

---

trakt/errors.py

Example:
```py
{'name': 'AUTHED_API_POST_LIMIT', 'period': 1, 'limit': 1, 'remaining': 0, 'until': '2024-01-08T22:31:48Z'}
```

Feature: Add details RateLimitException to parse x-ratelimit header

---

trakt/__version__.py

Currently not installable from source because version "Uknown" does not parse.
```
✖ pip install "trakt@https://github.com/glensc/python-trakt/archive/refs/tags/3.4.26.zip#egg=trakt" 
Collecting trakt@ https://github.com/glensc/python-trakt/archive/refs/tags/3.4.26.zip#egg=trakt
Using cached https://github.com/glensc/python-trakt/archive/refs/tags/3.4.26.zip
Installing build dependencies ... done
Getting requirements to build wheel ... error
error: subprocess-exited-with-error
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [27 lines of output]
Traceback (most recent call last):
File "/Users/glen/Library/Caches/glen/direnv/PlexTraktSync/python-3.8/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module> …
```

Fix: Allow install source with pip/pipenv

---

trakt/utils.py

Introduced in 6b86097ce87ad384e32842ed178e5e194ccfdcec (Aug 23, 2015)
Spec:
- https://en.wikipedia.org/wiki/ISO_8601

Fix: Remove superluous ":" from iso8601 timestamp

---

trakt/sync.py

Refs:
- https://github.com/Taxel/PlexTraktSync/issues/1805
- https://github.com/glensc/python-pytrakt/pull/25

Feature: Allow rate rated_at to be str or datetime

---

trakt/core.py

I noticed when setting up my own OAuth config storage that fetching the values of `core.OAUTH_REFRESH` and `core.OAUTH_EXPIRES_AT` after running `trakt.init` wasn't working. Turns out that's because while they were being set, they were only being set locally. I made them global in `oauth_auth()` and `get_device_token()` and it's working now.

Store OAuth global variables on initial auth

---

trakt/core.py

Since the default requests timeout is infinite individual calls might hang for a very long time if something in the network breaks. See also https://github.com/Taxel/PlexTraktSync/issues/2107.

Add timeout to all requests

---

.github/workflows/docs-build.yml
.github/workflows/docs-upload.yml

Take recommendations from coderabbit to accoiunt:
- https://github.com/glensc/python-pytrakt/pull/12

Ci: Use sphinx from pip

---

trakt/api.py

Even managed to get my token banned with too many requests

Fix oauth/token path, recursive overflow

---

trakt/api.py

Suggestion posted by coderabbit:
- https://github.com/glensc/python-pytrakt/pull/59#pullrequestreview-2545486419

Fix: Add max retries to token refresh

---

tests/test_api.py

Somehow left out when rebasing https://github.com/glensc/python-pytrakt/pull/51

Test: Add api test

---

trakt/api.py

Getting banned by trakt api if doing more than once.

Fix: Set max retries to 1

---

trakt/api.py

This would result http/client error:
> TypeError: expected string or bytes-like object
Example:
<details>
```
self = <urllib3.connection.HTTPSConnection object at 0x7f90e856e5e0>
header = b'trakt-api-key', values = [None], i = 0, one_value = None
def putheader(self, header, *values):
"""Send a request header line to the server.
For example: h.putheader('Accept', 'text/html')
"""
if self.__state != _CS_REQ_STARTED:
raise CannotSendHeader()
if hasattr(header, 'encode'):
header = header.encode('ascii')
if not _is_legal_header_name(header):
raise ValueError('Invalid header name %r' % (header,))
values = list(values)
for i, one_value in enumerate(values):
if hasattr(one_value, 'encode'):
values[i] = one_value.encode('latin-1')
elif isinstance(one_value, int):
values[i] = …
```

Fix: Skip sending trakt-api-key with None value

---

setup.py

Apparently it wasn't included in pip package at all.
Fix for https://github.com/Taxel/PlexTraktSync/issues/2167

Package trakt.auth subpackage

---

trakt/api.py

It doesn't need to be instance-specific, let it be class-specific.

Refactor: Move logging.getLogger to class static

---

trakt/errors.py

Refs
- https://github.com/Taxel/PlexTraktSync/issues/2162

Add AccountLimitExceeded error

---

setup.py

It's no longer updated, so don't bother adding it to the description:
- https://pypi.org/project/pytrakt/4.0.2/

Remove HISTORY.rst from pypi release page

---

trakt/api.py

AI overgenerated it, and didn't pay attention then

Doc: Remove un-needed Attributes documentation

---

trakt/api.py

Starting on March 4, 2025, a Trakt OAuth `access_token` will expire in 24 hours, instead of 3 months.
The current logic is to refresh the `access_token` if its expiration date is within next 2 days.
With current code, a 24h token would be immediately refreshed after being fetched. We do not want that.
This PR changes this delay from 2 days to 10 minutes.
>Why 10 minutes ?
This is a margin to be sure the token does not expire in the middle of a critical action such as a list sync/fetch/post.
It could be any other delay, but not bigger than 24h.
Refs :
- https://github.com/trakt/api-help/discussions/495

Reduce access_token refresh margin delay from 2 days to 10 minutes

---

trakt/api.py

Add improvements from coderabbit:
- https://github.com/glensc/python-pytrakt/pull/76

Use TOKEN_REFRESH_MARGIN constant

---

trakt/api.py

Refresh token can fail with error 400 or error 401 for many reasons, not only invalid _refresh_token_.
If refresh fails, an error should be logged.
And response body provides useful information.
Before PR:
```
INFO     OAuth token has expired, refreshing now...
CRITICAL Error running sync command: Trakt authentication error: Unauthorized - OAuth must be provided
```
After PR:
```
INFO     OAuth token has expired, refreshing now...
ERROR    401 - Unable to refresh expired OAuth token (invalid_client) Client authentication failed due to unknown
client, no client authentication included, or unsupported authentication method.
CRITICAL Error running sync command: Trakt authentication error: Unauthorized - OAuth must be provided
```
```
INFO     OAuth token has expired, refreshing now...
ERROR …
```

Log error when refresh token fails

---

.github/workflows/test.yml

See https://github.com/glensc/python-pytrakt/pull/81#issuecomment-3067059207
Drops 3.6 testing:
> Error: The version '3.6' with architecture 'x64' was not found for Ubuntu 22.04.
To find matching Python versions:
```sh
curl -O https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
cat versions-manifest.json | jq '.[] | select(.files[]? | select(.platform == "linux" and .platform_version == "22.04")) | .version' -r
```

CI: Switch ubuntu-20.04 with ubuntu-22.04 runner
